name: Spellcheck Action
on: push

jobs:
  build:
    name: Spellcheck
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: rojopolis/spellcheck-github-actions@0.11.0
      name: Spellcheck
      with:
        source_files: "**/*.md"
        task_name: Markdown

