name: Spellcheck Action
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main 

jobs:
  build:
    name: Spellcheck
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: rojopolis/spellcheck-github-actions@0.11.0
    - uses: dorny/paths-filter@v2.6.0
      id: filter
      with:
        list-files: shell
        filters: |
          markdown:
            - added|modified: '*.md'

